n1=int(input('digite um numero:'))
n2=int(input('digite um numero:'))
x=(n1+n2)
#print('a soma entre',n1,'e',n2,'é {}'.format(x))
#print('a soma entre {} e {} é {}'.format(n1,n2,x))
print(f'a soma entre {n1} e {n2} é {x}')